---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-manager
  labels:
    group: vault.crd.gocardless.com
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-manager
  labels:
    group: vault.crd.gocardless.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-manager
  labels:
    group: vault.crd.gocardless.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-manager
subjects:
  - kind: ServiceAccount
    name: vault-manager
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-manager-webhook
  labels:
    group: vault.crd.gocardless.com
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - theatre-vault-manager-webhook
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-manager-webhook
  labels:
    group: vault.crd.gocardless.com
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-manager-webhook
subjects:
  - kind: ServiceAccount
    name: vault-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-manager-leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: theatre-leader-election
subjects:
  - kind: ServiceAccount
    name: vault-manager
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-manager
spec:
  dnsNames:
    - theatre-vault-manager.theatre-system.svc
  issuerRef:
    kind: Issuer
    name: theatre-webhooks
  secretName: theatre-vault-manager-certificate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-manager
  labels:
    group: vault.crd.gocardless.com
spec:
  serviceName: vault-manager
  replicas: 1
  volumeClaimTemplates: []
  selector:
    matchLabels:
      group: vault.crd.gocardless.com
  template:
    metadata:
      labels:
        group: vault.crd.gocardless.com
    spec:
      serviceAccountName: vault-manager
      terminationGracePeriodSeconds: 10
      containers:
        - command:
            - /usr/local/bin/vault-manager
          args:
            - --theatre-image=THEATRE_IMAGE_PLACEHOLDER
            - --metrics-address=0.0.0.0
          image: eu.gcr.io/gc-containers/gocardless/theatre:latest
          imagePullPolicy: Always
          name: manager
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: https
              containerPort: 443
            - name: http-metrics
              containerPort: 9525
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: theatre-vault-manager-certificate
---
apiVersion: v1
kind: Service
metadata:
  name: vault-manager
spec:
  selector:
    group: vault.crd.gocardless.com
  ports:
    - port: 443
      targetPort: 443
