# View goreleaser docs for configuration settings
# https://goreleaser.com

---
project_name: theatre

builds:
  - &commonBuildConfig
    id: theatre-consoles
    binary: theatre-consoles
    main: cmd/theatre-consoles/main.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
    ldflags: >
      -X github.com/gocardless/theatre/v4/cmd.Version={{.Version}}
      -X github.com/gocardless/theatre/v4/cmd.Commit={{.Commit}}
      -X github.com/gocardless/theatre/v4/cmd.Date={{.Date}}
      -a
      -installsuffix cgo
    env:
      - CGO_ENABLED=0

  - <<: *commonBuildConfig
    id: theatre-secrets
    binary: theatre-secrets
    main: cmd/theatre-secrets/main.go

  - <<: *commonBuildConfig
    id: vault-manager
    binary: vault-manager
    main: cmd/vault-manager/main.go

  - <<: *commonBuildConfig
    id: workloads-manager
    binary: workloads-manager
    main: cmd/workloads-manager/main.go
