---
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag', 'eu.gcr.io/$PROJECT_ID/theatre:$SHORT_SHA', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker/theatre:$COMMIT_SHA'
    '--file', 'Dockerfile',
    '.'
  ]

images: [
  'eu.gcr.io/$PROJECT_ID/theatre:$COMMIT_SHA',
  'europe-west1-docker.pkg.dev/$PROJECT_ID/docker/theatre:$COMMIT_SHA'
]

options:
  machineType: 'E2_MEDIUM'
