---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      controller: vault-manager
      group: vault.crd.gocardless.com
  template:
    metadata:
      labels:
        controller: vault-manager
        group: vault.crd.gocardless.com
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
          args:
            - --theatre-image=$(THEATRE_IMAGE)
            - --metrics-address=0.0.0.0
          resources:
            requests:
              cpu: "100m"
