---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: workloads-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      controller: workloads-manager
      group: workloads.crd.gocardless.com
  template:
    metadata:
      labels:
        controller: workloads-manager
        group: workloads.crd.gocardless.com
    spec:
      containers:
        - name: manager
          image: theatre:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "100m"
