/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// ReleaseSpec defines the desired state of Release
type ReleaseSpec struct {
	// UtopiaServiceTargetRelease specifies the utopia.services[].spec.environments[].targets[].release
	// field of each utopia service. These are namespace unique and are used to identify the release
	// +kubebuilder:validation:Required
	UtopiaServiceTargetRelease string `json:"utopiaServiceTargetRelease"`
	// ApplicationRevision specifies the application revision of this release i.e.
	// a commit SHA from the application repository. The commit SHA is also used
	// to tag the application image in the container registry.
	// +kubebuilder:validation:Required
	ApplicationRevision Revision `json:"applicationRevision"`
	// InfrastructureRevision specifies the infrastructure revision of this
	// release i.e. a commit SHA from the infrastructure repository
	// (gocardless/anu). The commit SHA is also used to tag the infrastructure
	// image in the container registry.
	// +kubebuilder:validation:Required
	InfrastructureRevision Revision `json:"infrastructureRevision,omitempty"`
}

type Revision struct {
	// ID is the unique identifier of the revision (i.e. commit SHA). The field
	// is required.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:Pattern=`^[a-f0-9]{40}$`
	ID string `json:"id"`
	// Author is the author of the commit, if available. The field is optional.
	// +kubebuilder:validation:Optional
	Author string `json:"author,omitempty"`
	// Branch is the branch of the commit, if available. The field is optional.
	// +kubebuilder:validation:Optional
	Branch string `json:"branch,omitempty"`
	// Message is the message of the commit, if available. The field is optional.
	// +kubebuilder:validation:Optional
	Message string `json:"message,omitempty"`
	// Repository is the repository of the commit, if available. The field is optional.
	// +kubebuilder:validation:Optional
	Repository string `json:"repository,omitempty"`
}

// ReleaseStatus defines the observed state of Release.

type Phase string

const (
	PhaseActive   Phase = "Active"
	PhaseInactive Phase = "Inactive"
)

type ReleaseStatus struct {
	// Phase is the current phase of the release. Active indicates the release
	// is currently live in the cluster, Inactive indicates the release is no
	// longer the latest release.
	// +kubebuilder:validation:Enum:=Active;Inactive
	// +kubebuilder:validation:Required
	Phase Phase `json:"phase"`
	// Message is a human-readable message indicating the state of the release.
	// +kubebuilder:validation:Optional
	Message string `json:"message,omitempty"`
	// LastAppliedTime is the last time the release was applied to the cluster.
	// +kubebuilder:validation:Optional
	LastAppliedTime metav1.Time `json:"lastAppliedTime,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:selectablefield:JSONPath=".spec.utopiaServiceTargetRelease"
// TODO: check if you want to move this validation elsewhere, maybe in code instead of annotations
// +kubebuilder:validation:XValidation:rule="!has(oldSelf.metadata.name) || self.metadata.name == oldSelf.metadata.name",message="Release name is immutable and auto-generated by webhook"
// Release is the Schema for the releases API.
// NOTE: The metadata.name field is auto-generated by the mutating webhook
// based on utopiaServiceTargetRelease and revision IDs. Leave it empty on creation.
type Release struct {
	metav1.TypeMeta `json:",inline"`

	// Metadata is a standard object metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty,omitzero"`

	// Spec defines the desired state of Release
	// +required
	Spec ReleaseSpec `json:"spec"`

	// Status defines the observed state of Release
	// +optional
	Status ReleaseStatus `json:"status,omitempty,omitzero"`
}

// +kubebuilder:object:root=true

// ReleaseList contains a list of Release
type ReleaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Release `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Release{}, &ReleaseList{})
}
