/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gocardless/theatre/pkg/apis/workloads/v1alpha1"
	scheme "github.com/gocardless/theatre/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ConsoleAuthorisationsGetter has a method to return a ConsoleAuthorisationInterface.
// A group's client should implement this interface.
type ConsoleAuthorisationsGetter interface {
	ConsoleAuthorisations(namespace string) ConsoleAuthorisationInterface
}

// ConsoleAuthorisationInterface has methods to work with ConsoleAuthorisation resources.
type ConsoleAuthorisationInterface interface {
	Create(*v1alpha1.ConsoleAuthorisation) (*v1alpha1.ConsoleAuthorisation, error)
	Update(*v1alpha1.ConsoleAuthorisation) (*v1alpha1.ConsoleAuthorisation, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ConsoleAuthorisation, error)
	List(opts v1.ListOptions) (*v1alpha1.ConsoleAuthorisationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsoleAuthorisation, err error)
	ConsoleAuthorisationExpansion
}

// consoleAuthorisations implements ConsoleAuthorisationInterface
type consoleAuthorisations struct {
	client rest.Interface
	ns     string
}

// newConsoleAuthorisations returns a ConsoleAuthorisations
func newConsoleAuthorisations(c *WorkloadsV1alpha1Client, namespace string) *consoleAuthorisations {
	return &consoleAuthorisations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the consoleAuthorisation, and returns the corresponding consoleAuthorisation object, and an error if there is any.
func (c *consoleAuthorisations) Get(name string, options v1.GetOptions) (result *v1alpha1.ConsoleAuthorisation, err error) {
	result = &v1alpha1.ConsoleAuthorisation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ConsoleAuthorisations that match those selectors.
func (c *consoleAuthorisations) List(opts v1.ListOptions) (result *v1alpha1.ConsoleAuthorisationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ConsoleAuthorisationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested consoleAuthorisations.
func (c *consoleAuthorisations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a consoleAuthorisation and creates it.  Returns the server's representation of the consoleAuthorisation, and an error, if there is any.
func (c *consoleAuthorisations) Create(consoleAuthorisation *v1alpha1.ConsoleAuthorisation) (result *v1alpha1.ConsoleAuthorisation, err error) {
	result = &v1alpha1.ConsoleAuthorisation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		Body(consoleAuthorisation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a consoleAuthorisation and updates it. Returns the server's representation of the consoleAuthorisation, and an error, if there is any.
func (c *consoleAuthorisations) Update(consoleAuthorisation *v1alpha1.ConsoleAuthorisation) (result *v1alpha1.ConsoleAuthorisation, err error) {
	result = &v1alpha1.ConsoleAuthorisation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		Name(consoleAuthorisation.Name).
		Body(consoleAuthorisation).
		Do().
		Into(result)
	return
}

// Delete takes name of the consoleAuthorisation and deletes it. Returns an error if one occurs.
func (c *consoleAuthorisations) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *consoleAuthorisations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consoleauthorisations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched consoleAuthorisation.
func (c *consoleAuthorisations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsoleAuthorisation, err error) {
	result = &v1alpha1.ConsoleAuthorisation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("consoleauthorisations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
