/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/gocardless/theatre/pkg/apis/workloads/v1alpha1"
	scheme "github.com/gocardless/theatre/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ConsoleTemplatesGetter has a method to return a ConsoleTemplateInterface.
// A group's client should implement this interface.
type ConsoleTemplatesGetter interface {
	ConsoleTemplates(namespace string) ConsoleTemplateInterface
}

// ConsoleTemplateInterface has methods to work with ConsoleTemplate resources.
type ConsoleTemplateInterface interface {
	Create(*v1alpha1.ConsoleTemplate) (*v1alpha1.ConsoleTemplate, error)
	Update(*v1alpha1.ConsoleTemplate) (*v1alpha1.ConsoleTemplate, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ConsoleTemplate, error)
	List(opts v1.ListOptions) (*v1alpha1.ConsoleTemplateList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsoleTemplate, err error)
	ConsoleTemplateExpansion
}

// consoleTemplates implements ConsoleTemplateInterface
type consoleTemplates struct {
	client rest.Interface
	ns     string
}

// newConsoleTemplates returns a ConsoleTemplates
func newConsoleTemplates(c *WorkloadsV1alpha1Client, namespace string) *consoleTemplates {
	return &consoleTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the consoleTemplate, and returns the corresponding consoleTemplate object, and an error if there is any.
func (c *consoleTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.ConsoleTemplate, err error) {
	result = &v1alpha1.ConsoleTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consoletemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(context.TODO()).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ConsoleTemplates that match those selectors.
func (c *consoleTemplates) List(opts v1.ListOptions) (result *v1alpha1.ConsoleTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ConsoleTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consoletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(context.TODO()).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested consoleTemplates.
func (c *consoleTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("consoletemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(context.TODO())
}

// Create takes the representation of a consoleTemplate and creates it.  Returns the server's representation of the consoleTemplate, and an error, if there is any.
func (c *consoleTemplates) Create(consoleTemplate *v1alpha1.ConsoleTemplate) (result *v1alpha1.ConsoleTemplate, err error) {
	result = &v1alpha1.ConsoleTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("consoletemplates").
		Body(consoleTemplate).
		Do(context.TODO()).
		Into(result)
	return
}

// Update takes the representation of a consoleTemplate and updates it. Returns the server's representation of the consoleTemplate, and an error, if there is any.
func (c *consoleTemplates) Update(consoleTemplate *v1alpha1.ConsoleTemplate) (result *v1alpha1.ConsoleTemplate, err error) {
	result = &v1alpha1.ConsoleTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consoletemplates").
		Name(consoleTemplate.Name).
		Body(consoleTemplate).
		Do(context.TODO()).
		Into(result)
	return
}

// Delete takes name of the consoleTemplate and deletes it. Returns an error if one occurs.
func (c *consoleTemplates) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consoletemplates").
		Name(name).
		Body(options).
		Do(context.TODO()).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *consoleTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consoletemplates").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do(context.TODO()).
		Error()
}

// Patch applies the patch and returns the patched consoleTemplate.
func (c *consoleTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsoleTemplate, err error) {
	result = &v1alpha1.ConsoleTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("consoletemplates").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do(context.TODO()).
		Into(result)
	return
}
