/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/lawrencejones/theatre/pkg/apis/rbac/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSudoRoleBindings implements SudoRoleBindingInterface
type FakeSudoRoleBindings struct {
	Fake *FakeRbacV1alpha1
	ns   string
}

var sudorolebindingsResource = schema.GroupVersionResource{Group: "rbac.lawrjone.xyz", Version: "v1alpha1", Resource: "sudorolebindings"}

var sudorolebindingsKind = schema.GroupVersionKind{Group: "rbac.lawrjone.xyz", Version: "v1alpha1", Kind: "SudoRoleBinding"}

// Get takes name of the sudoRoleBinding, and returns the corresponding sudoRoleBinding object, and an error if there is any.
func (c *FakeSudoRoleBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.SudoRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sudorolebindingsResource, c.ns, name), &v1alpha1.SudoRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SudoRoleBinding), err
}

// List takes label and field selectors, and returns the list of SudoRoleBindings that match those selectors.
func (c *FakeSudoRoleBindings) List(opts v1.ListOptions) (result *v1alpha1.SudoRoleBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sudorolebindingsResource, sudorolebindingsKind, c.ns, opts), &v1alpha1.SudoRoleBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SudoRoleBindingList{ListMeta: obj.(*v1alpha1.SudoRoleBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.SudoRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sudoRoleBindings.
func (c *FakeSudoRoleBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sudorolebindingsResource, c.ns, opts))

}

// Create takes the representation of a sudoRoleBinding and creates it.  Returns the server's representation of the sudoRoleBinding, and an error, if there is any.
func (c *FakeSudoRoleBindings) Create(sudoRoleBinding *v1alpha1.SudoRoleBinding) (result *v1alpha1.SudoRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sudorolebindingsResource, c.ns, sudoRoleBinding), &v1alpha1.SudoRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SudoRoleBinding), err
}

// Update takes the representation of a sudoRoleBinding and updates it. Returns the server's representation of the sudoRoleBinding, and an error, if there is any.
func (c *FakeSudoRoleBindings) Update(sudoRoleBinding *v1alpha1.SudoRoleBinding) (result *v1alpha1.SudoRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sudorolebindingsResource, c.ns, sudoRoleBinding), &v1alpha1.SudoRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SudoRoleBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSudoRoleBindings) UpdateStatus(sudoRoleBinding *v1alpha1.SudoRoleBinding) (*v1alpha1.SudoRoleBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sudorolebindingsResource, "status", c.ns, sudoRoleBinding), &v1alpha1.SudoRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SudoRoleBinding), err
}

// Delete takes name of the sudoRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeSudoRoleBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sudorolebindingsResource, c.ns, name), &v1alpha1.SudoRoleBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSudoRoleBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sudorolebindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SudoRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched sudoRoleBinding.
func (c *FakeSudoRoleBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SudoRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sudorolebindingsResource, c.ns, name, data, subresources...), &v1alpha1.SudoRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SudoRoleBinding), err
}
