---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: directoryrolebindings.rbac.gocardless.io
spec:
  group: rbac.gocardless.io
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: directoryrolebindings
    singular: directoryrolebinding
    kind: DirectoryRoleBinding
    shortNames:
      - drb
      - drbs
