/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gocardless/theatre/pkg/apis/workloads/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConsoleTemplates implements ConsoleTemplateInterface
type FakeConsoleTemplates struct {
	Fake *FakeWorkloadsV1alpha1
	ns   string
}

var consoletemplatesResource = schema.GroupVersionResource{Group: "workloads.crd.gocardless.com", Version: "v1alpha1", Resource: "consoletemplates"}

var consoletemplatesKind = schema.GroupVersionKind{Group: "workloads.crd.gocardless.com", Version: "v1alpha1", Kind: "ConsoleTemplate"}

// Get takes name of the consoleTemplate, and returns the corresponding consoleTemplate object, and an error if there is any.
func (c *FakeConsoleTemplates) Get(name string, options v1.GetOptions) (result *v1alpha1.ConsoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(consoletemplatesResource, c.ns, name), &v1alpha1.ConsoleTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsoleTemplate), err
}

// List takes label and field selectors, and returns the list of ConsoleTemplates that match those selectors.
func (c *FakeConsoleTemplates) List(opts v1.ListOptions) (result *v1alpha1.ConsoleTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(consoletemplatesResource, consoletemplatesKind, c.ns, opts), &v1alpha1.ConsoleTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ConsoleTemplateList{ListMeta: obj.(*v1alpha1.ConsoleTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.ConsoleTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested consoleTemplates.
func (c *FakeConsoleTemplates) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(consoletemplatesResource, c.ns, opts))

}

// Create takes the representation of a consoleTemplate and creates it.  Returns the server's representation of the consoleTemplate, and an error, if there is any.
func (c *FakeConsoleTemplates) Create(consoleTemplate *v1alpha1.ConsoleTemplate) (result *v1alpha1.ConsoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(consoletemplatesResource, c.ns, consoleTemplate), &v1alpha1.ConsoleTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsoleTemplate), err
}

// Update takes the representation of a consoleTemplate and updates it. Returns the server's representation of the consoleTemplate, and an error, if there is any.
func (c *FakeConsoleTemplates) Update(consoleTemplate *v1alpha1.ConsoleTemplate) (result *v1alpha1.ConsoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(consoletemplatesResource, c.ns, consoleTemplate), &v1alpha1.ConsoleTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsoleTemplate), err
}

// Delete takes name of the consoleTemplate and deletes it. Returns an error if one occurs.
func (c *FakeConsoleTemplates) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(consoletemplatesResource, c.ns, name), &v1alpha1.ConsoleTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConsoleTemplates) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(consoletemplatesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ConsoleTemplateList{})
	return err
}

// Patch applies the patch and returns the patched consoleTemplate.
func (c *FakeConsoleTemplates) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ConsoleTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(consoletemplatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ConsoleTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ConsoleTemplate), err
}
