/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/lawrencejones/theatre/pkg/apis/rbac/v1alpha1"
	scheme "github.com/lawrencejones/theatre/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DirectoryRoleBindingsGetter has a method to return a DirectoryRoleBindingInterface.
// A group's client should implement this interface.
type DirectoryRoleBindingsGetter interface {
	DirectoryRoleBindings(namespace string) DirectoryRoleBindingInterface
}

// DirectoryRoleBindingInterface has methods to work with DirectoryRoleBinding resources.
type DirectoryRoleBindingInterface interface {
	Create(*v1alpha1.DirectoryRoleBinding) (*v1alpha1.DirectoryRoleBinding, error)
	Update(*v1alpha1.DirectoryRoleBinding) (*v1alpha1.DirectoryRoleBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.DirectoryRoleBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.DirectoryRoleBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DirectoryRoleBinding, err error)
	DirectoryRoleBindingExpansion
}

// directoryRoleBindings implements DirectoryRoleBindingInterface
type directoryRoleBindings struct {
	client rest.Interface
	ns     string
}

// newDirectoryRoleBindings returns a DirectoryRoleBindings
func newDirectoryRoleBindings(c *RbacV1alpha1Client, namespace string) *directoryRoleBindings {
	return &directoryRoleBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the directoryRoleBinding, and returns the corresponding directoryRoleBinding object, and an error if there is any.
func (c *directoryRoleBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.DirectoryRoleBinding, err error) {
	result = &v1alpha1.DirectoryRoleBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DirectoryRoleBindings that match those selectors.
func (c *directoryRoleBindings) List(opts v1.ListOptions) (result *v1alpha1.DirectoryRoleBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DirectoryRoleBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested directoryRoleBindings.
func (c *directoryRoleBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a directoryRoleBinding and creates it.  Returns the server's representation of the directoryRoleBinding, and an error, if there is any.
func (c *directoryRoleBindings) Create(directoryRoleBinding *v1alpha1.DirectoryRoleBinding) (result *v1alpha1.DirectoryRoleBinding, err error) {
	result = &v1alpha1.DirectoryRoleBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		Body(directoryRoleBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a directoryRoleBinding and updates it. Returns the server's representation of the directoryRoleBinding, and an error, if there is any.
func (c *directoryRoleBindings) Update(directoryRoleBinding *v1alpha1.DirectoryRoleBinding) (result *v1alpha1.DirectoryRoleBinding, err error) {
	result = &v1alpha1.DirectoryRoleBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		Name(directoryRoleBinding.Name).
		Body(directoryRoleBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the directoryRoleBinding and deletes it. Returns an error if one occurs.
func (c *directoryRoleBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *directoryRoleBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("directoryrolebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched directoryRoleBinding.
func (c *directoryRoleBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DirectoryRoleBinding, err error) {
	result = &v1alpha1.DirectoryRoleBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("directoryrolebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
