/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/lawrencejones/theatre/pkg/apis/rbac/v1alpha1"
	scheme "github.com/lawrencejones/theatre/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SudoRolesGetter has a method to return a SudoRoleInterface.
// A group's client should implement this interface.
type SudoRolesGetter interface {
	SudoRoles(namespace string) SudoRoleInterface
}

// SudoRoleInterface has methods to work with SudoRole resources.
type SudoRoleInterface interface {
	Create(*v1alpha1.SudoRole) (*v1alpha1.SudoRole, error)
	Update(*v1alpha1.SudoRole) (*v1alpha1.SudoRole, error)
	UpdateStatus(*v1alpha1.SudoRole) (*v1alpha1.SudoRole, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.SudoRole, error)
	List(opts v1.ListOptions) (*v1alpha1.SudoRoleList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SudoRole, err error)
	SudoRoleExpansion
}

// sudoRoles implements SudoRoleInterface
type sudoRoles struct {
	client rest.Interface
	ns     string
}

// newSudoRoles returns a SudoRoles
func newSudoRoles(c *RbacV1alpha1Client, namespace string) *sudoRoles {
	return &sudoRoles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the sudoRole, and returns the corresponding sudoRole object, and an error if there is any.
func (c *sudoRoles) Get(name string, options v1.GetOptions) (result *v1alpha1.SudoRole, err error) {
	result = &v1alpha1.SudoRole{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sudoroles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SudoRoles that match those selectors.
func (c *sudoRoles) List(opts v1.ListOptions) (result *v1alpha1.SudoRoleList, err error) {
	result = &v1alpha1.SudoRoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("sudoroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested sudoRoles.
func (c *sudoRoles) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("sudoroles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a sudoRole and creates it.  Returns the server's representation of the sudoRole, and an error, if there is any.
func (c *sudoRoles) Create(sudoRole *v1alpha1.SudoRole) (result *v1alpha1.SudoRole, err error) {
	result = &v1alpha1.SudoRole{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("sudoroles").
		Body(sudoRole).
		Do().
		Into(result)
	return
}

// Update takes the representation of a sudoRole and updates it. Returns the server's representation of the sudoRole, and an error, if there is any.
func (c *sudoRoles) Update(sudoRole *v1alpha1.SudoRole) (result *v1alpha1.SudoRole, err error) {
	result = &v1alpha1.SudoRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sudoroles").
		Name(sudoRole.Name).
		Body(sudoRole).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *sudoRoles) UpdateStatus(sudoRole *v1alpha1.SudoRole) (result *v1alpha1.SudoRole, err error) {
	result = &v1alpha1.SudoRole{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("sudoroles").
		Name(sudoRole.Name).
		SubResource("status").
		Body(sudoRole).
		Do().
		Into(result)
	return
}

// Delete takes name of the sudoRole and deletes it. Returns an error if one occurs.
func (c *sudoRoles) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sudoroles").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *sudoRoles) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("sudoroles").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched sudoRole.
func (c *sudoRoles) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SudoRole, err error) {
	result = &v1alpha1.SudoRole{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("sudoroles").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
